# Generated by Django 4.2.2 on 2023-07-01 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_in_shopping_cart', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Список продуктов пользователя',
                'verbose_name_plural': 'Списки продуктов пользователей',
            },
        ),
        migrations.RemoveField(
            model_name='shoppingcarduser',
            name='shopping_card',
        ),
        migrations.RemoveField(
            model_name='shoppingcarduser',
            name='user',
        ),
        migrations.DeleteModel(
            name='ShoppingCard',
        ),
        migrations.DeleteModel(
            name='ShoppingCardUser',
        ),
    ]
