# Generated by Django 4.2.2 on 2023-06-27 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_recipe_author_alter_tagrecipe_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='название')),
                ('image', models.ImageField(upload_to='favorite_recipes/images', verbose_name='изображение')),
                ('cooking_time', models.IntegerField(validators=[recipes.models.validate_cooking_time], verbose_name='Время приготовления (в минутах)')),
            ],
            options={
                'verbose_name': 'Список продуктов',
                'verbose_name_plural': 'Списки продуктов',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='recipes.shoppingcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Список продуктов пользователя',
                'verbose_name_plural': 'Списки продуктов пользователей',
            },
        ),
        migrations.CreateModel(
            name='FavoriteRecipeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_favorite', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранный рецепт',
                'verbose_name_plural': 'Избранные рецепты',
            },
        ),
    ]
