# Generated by Django 4.2.2 on 2023-06-26 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_fisrt_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Введите верный адрес электронной почты')], verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(':^[\\w.@+-]+$', 'Введите допустимое имя пользователя.', 'invalid')]),
        ),
    ]
